name: pr
on:
  push:
    branch: actions
jobs:
  pr:
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        target:
          - os: "linux"
            arch: "386"
            out: "recovery-tool-linux32"
          - os: "linux"
            arch: "amd64"
            out: "recovery-tool-linux64"
          - os: "windows"
            arch: "386"
            cc: "i686-w64-mingw32-gcc"
            out: "recovery-tool-windows32.exe"
          - os: "windows"
            arch: "amd64"
            cc: "x86_64-w64-mingw32-gcc"
            out: "recovery-tool-windows64.exe"

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6
        with:
          buildkitd-flags: --debug

      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Create output dir
        run: |
          mkdir -p bin

      - name: Build
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          file: Dockerfile
          context: .
          outputs: bin
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            cc=${{ matrix.target.cc }}
            os=${{ matrix.target.os }}
            arch=${{ matrix.target.arch }}
            out=${{ matrix.target.out }}

      - name: Upload binary
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          name: ${{ matrix.target.out }}
          path: bin/${{ matrix.target.out }}
